export interface WCTeam {
  abbr: string
  flag: string
  name: string
}

export const WC_TEAMS: WCTeam[] = [
  { abbr: 'ARG', flag: '🇦🇷', name: 'Argentina' },
  { abbr: 'AUS', flag: '🇦🇺', name: 'Australia' },
  { abbr: 'AUT', flag: '🇦🇹', name: 'Austria' },
  { abbr: 'BEL', flag: '🇧🇪', name: 'Belgium' },
  { abbr: 'BOL', flag: '🇧🇴', name: 'Bolivia' },
  { abbr: 'BRA', flag: '🇧🇷', name: 'Brazil' },
  { abbr: 'CAN', flag: '🇨🇦', name: 'Canada' },
  { abbr: 'CHI', flag: '🇨🇱', name: 'Chile' },
  { abbr: 'CIV', flag: '🇨🇮', name: "Côte d'Ivoire" },
  { abbr: 'CMR', flag: '🇨🇲', name: 'Cameroon' },
  { abbr: 'COD', flag: '🇨🇩', name: 'DR Congo' },
  { abbr: 'COL', flag: '🇨🇴', name: 'Colombia' },
  { abbr: 'CRC', flag: '🇨🇷', name: 'Costa Rica' },
  { abbr: 'CRO', flag: '🇭🇷', name: 'Croatia' },
  { abbr: 'CZE', flag: '🇨🇿', name: 'Czech Republic' },
  { abbr: 'DEN', flag: '🇩🇰', name: 'Denmark' },
  { abbr: 'ECU', flag: '🇪🇨', name: 'Ecuador' },
  { abbr: 'EGY', flag: '🇪🇬', name: 'Egypt' },
  { abbr: 'ENG', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿', name: 'England' },
  { abbr: 'ESP', flag: '🇪🇸', name: 'Spain' },
  { abbr: 'FRA', flag: '🇫🇷', name: 'France' },
  { abbr: 'GER', flag: '🇩🇪', name: 'Germany' },
  { abbr: 'GHA', flag: '🇬🇭', name: 'Ghana' },
  { abbr: 'GRE', flag: '🇬🇷', name: 'Greece' },
  { abbr: 'HON', flag: '🇭🇳', name: 'Honduras' },
  { abbr: 'HUN', flag: '🇭🇺', name: 'Hungary' },
  { abbr: 'IRL', flag: '🇮🇪', name: 'Ireland' },
  { abbr: 'IRN', flag: '🇮🇷', name: 'Iran' },
  { abbr: 'IRQ', flag: '🇮🇶', name: 'Iraq' },
  { abbr: 'ISL', flag: '🇮🇸', name: 'Iceland' },
  { abbr: 'JAM', flag: '🇯🇲', name: 'Jamaica' },
  { abbr: 'JOR', flag: '🇯🇴', name: 'Jordan' },
  { abbr: 'JPN', flag: '🇯🇵', name: 'Japan' },
  { abbr: 'KOR', flag: '🇰🇷', name: 'South Korea' },
  { abbr: 'MAR', flag: '🇲🇦', name: 'Morocco' },
  { abbr: 'MEX', flag: '🇲🇽', name: 'Mexico' },
  { abbr: 'MLI', flag: '🇲🇱', name: 'Mali' },
  { abbr: 'NED', flag: '🇳🇱', name: 'Netherlands' },
  { abbr: 'NGA', flag: '🇳🇬', name: 'Nigeria' },
  { abbr: 'NOR', flag: '🇳🇴', name: 'Norway' },
  { abbr: 'NZL', flag: '🇳🇿', name: 'New Zealand' },
  { abbr: 'PAN', flag: '🇵🇦', name: 'Panama' },
  { abbr: 'PAR', flag: '🇵🇾', name: 'Paraguay' },
  { abbr: 'POL', flag: '🇵🇱', name: 'Poland' },
  { abbr: 'POR', flag: '🇵🇹', name: 'Portugal' },
  { abbr: 'QAT', flag: '🇶🇦', name: 'Qatar' },
  { abbr: 'ROU', flag: '🇷🇴', name: 'Romania' },
  { abbr: 'SAU', flag: '🇸🇦', name: 'Saudi Arabia' },
  { abbr: 'SCO', flag: '🏴󠁧󠁢󠁳󠁣󠁴󠁿', name: 'Scotland' },
  { abbr: 'SEN', flag: '🇸🇳', name: 'Senegal' },
  { abbr: 'SRB', flag: '🇷🇸', name: 'Serbia' },
  { abbr: 'SUI', flag: '🇨🇭', name: 'Switzerland' },
  { abbr: 'SVK', flag: '🇸🇰', name: 'Slovakia' },
  { abbr: 'SVN', flag: '🇸🇮', name: 'Slovenia' },
  { abbr: 'TRI', flag: '🇹🇹', name: 'Trinidad & Tobago' },
  { abbr: 'TUN', flag: '🇹🇳', name: 'Tunisia' },
  { abbr: 'TUR', flag: '🇹🇷', name: 'Turkey' },
  { abbr: 'UKR', flag: '🇺🇦', name: 'Ukraine' },
  { abbr: 'URU', flag: '🇺🇾', name: 'Uruguay' },
  { abbr: 'USA', flag: '🇺🇸', name: 'United States' },
  { abbr: 'UZB', flag: '🇺🇿', name: 'Uzbekistan' },
  { abbr: 'VEN', flag: '🇻🇪', name: 'Venezuela' },
  { abbr: 'WAL', flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿', name: 'Wales' },
]

export function getTeamFlag(abbr: string): string {
  return WC_TEAMS.find((t) => t.abbr === abbr)?.flag ?? '🏳️'
}
